version: "3.9"

services:
  nginx:
    build:
      context: .
    image: nginx:1.23.3
    environment:
      - "TIMEZONE=Asia/Shanghai"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ${WEB_ROOT}:/webroot/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  serv:
    image: php_cli:8.2.10
    build:
      context: .
      dockerfile: ./phpcli/dockerfile
    restart: no
    volumes:
      - ${SERV_ROOT}:/app/
      - ./phpcli/php.ini:/usr/local/etc/php/php.ini
      - ./phpcli/conf.d/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./phpcli/conf.d/docker-php-ext-swoole.ini:/usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
    ports:
      - "8081:8001"
      - "8082:8002"
    networks:
      app_net:
    command: [ "php","/app/bin/dev","start" ]
    depends_on:
      - redis
      - rabbitmq
  #      - mysql

  redis:
    #    image: redis/redis-stack:6.2.6-v9-arm64
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      app_net:
    environment:
      - TZ=Asia/Shanghai

  rabbitmq:
    image: rabbitmq:3.12.2-management-alpine
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_ERLANG_COOKIE=ffserv
      - TZ=Asia/Shanghai
    volumes:
      - ./data/rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 111111
        hard: 111111
    networks:
      app_net:

volumes:
  es_data:
    driver: local

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.255.255.0/24
